// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA9flyaZr5Yh7PxAvJ9gF9neDWTxwth30',
    appId: '1:128318604608:web:4d97a2d9412a487af426a5',
    messagingSenderId: '128318604608',
    projectId: 'ku-reporting-authen',
    authDomain: 'ku-reporting-authen.firebaseapp.com',
    storageBucket: 'ku-reporting-authen.firebasestorage.app',
    measurementId: 'G-761SFZBP73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX_bgaQn99bVjvamS87KWY_FUvAYyKNYQ',
    appId: '1:128318604608:android:b64fc0d367759e04f426a5',
    messagingSenderId: '128318604608',
    projectId: 'ku-reporting-authen',
    storageBucket: 'ku-reporting-authen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3M79ZeMPBNTOiC7ePeoNPRRg1h0kkBto',
    appId: '1:128318604608:ios:0cd7d06e42cb50aff426a5',
    messagingSenderId: '128318604608',
    projectId: 'ku-reporting-authen',
    storageBucket: 'ku-reporting-authen.firebasestorage.app',
    iosBundleId: 'com.example.kuReportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3M79ZeMPBNTOiC7ePeoNPRRg1h0kkBto',
    appId: '1:128318604608:ios:0cd7d06e42cb50aff426a5',
    messagingSenderId: '128318604608',
    projectId: 'ku-reporting-authen',
    storageBucket: 'ku-reporting-authen.firebasestorage.app',
    iosBundleId: 'com.example.kuReportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA9flyaZr5Yh7PxAvJ9gF9neDWTxwth30',
    appId: '1:128318604608:web:18dbe63c999da6b0f426a5',
    messagingSenderId: '128318604608',
    projectId: 'ku-reporting-authen',
    authDomain: 'ku-reporting-authen.firebaseapp.com',
    storageBucket: 'ku-reporting-authen.firebasestorage.app',
    measurementId: 'G-WRQ3M6P75T',
  );
}
